- name: vCloudDirectorAnsible
  hosts: localhost
  environment:
        env_user: rbaena
        env_password: P0de5erV0ce!!
        env_host: vmware.cloudmandic.com.br            
        env_org: Baena             
        env_verify_ssl_certs: False
  tasks:
   - name: create vapp
     vcd_vapp:
       vapp_name: "{{item.name}}"
       vdc: "Baena"
       power_on: true
       network: "netprod"
       state: "present"
     with_items:
     - { name: k8s-masters }
     - { name: k8s-nodes }

   - name: create vapp vm from catalog
     vcd_vapp_vm:
      target_vm_name: "{{item.name}}"
      target_vapp: "{{item.vapp}}"
      source_vdc: "Baena"
      target_vdc: "Baena"
      source_catalog_name: "baena_linux"
      source_template_name: Ubuntu16
      source_vm_name: Ubuntu16
      hostname: "{{item.name}}"
      vmpassword: "P@ssw0rd" 
      vmpassword_auto: "false"
      vmpassword_reset: "false"
      ip_allocation_mode: "pool"
      power_on: "true"
      all_eulas_accepted: "true"
      storage_profile: "SSD"
      network: "netprod"
      #cust_script: "test_script"
      deploy: true
      state: "present"
     with_items:
      - { name: master, vapp: k8s-masters }
      - { name: node01, vapp: k8s-nodes }
      - { name: node02, vapp: k8s-nodes }
      - { name: node03, vapp: k8s-nodes }
